### ISSUE TITLE
bug: potential race condition surrounding engineio connection

### ISSUE THREAD

**Issue by ethanholz** [taigrr/socketio#1]
Received the following surrounding a goroutine connection

```
panic: concurrent write to websocket connection
goroutine 20 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc00019eb40, 0x1, {0x0?, 0x7f230bb7e888?, 0x7f230bb75108?})
        /go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x50b
github.com/gorilla/websocket.(*messageWriter).Close(0xc00030c300?)
        /go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:731 +0x45
github.com/gorilla/websocket.(*Conn).beginMessage(0xc0002586e0, 0xc00030c300, 0x1)
        /go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:480 +0x42
github.com/gorilla/websocket.(*Conn).NextWriter(0xc0002586e0, 0x1)
        /go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:520 +0x45
github.com/pschlump/socketio/engineio/websocket.(*Server).NextWriter(0xc00029af88?, 0xc00029af34?, {0x7c808f, 0x4})
        /go/pkg/mod/github.com/pschlump/socketio@v0.0.0-20200510162242-2b534d03a6e0/engineio/websocket/server.go:61 +0x53
github.com/pschlump/socketio/engineio.(*serverConn).pingLoop(0xc0000d60d0)
        /go/pkg/mod/github.com/pschlump/socketio@v0.0.0-20200510162242-2b534d03a6e0/engineio/server_conn.go:360 +0x1ef
created by github.com/pschlump/socketio/engineio.newServerConn
        /go/pkg/mod/github.com/pschlump/socketio@v0.0.0-20200510162242-2b534d03a6e0/engineio/server_conn.go:110 +0x436
```

I believe this might be an issue with the pingLoop since the connection does not get properly locked after getting the current connection.

**Comment by taigrr** [comment]
Merged in #2
